<a href="https://colab.research.google.com/github/leoopl/DataScience/blob/main/CE_GA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import random

pop = np.random.randint(2, size=(10,8))
pop

array([[1, 0, 0, 1, 0, 0, 1, 1],
       [0, 0, 0, 1, 0, 1, 1, 0],
       [0, 1, 0, 0, 1, 0, 0, 0],
       [1, 1, 0, 1, 1, 0, 1, 0],
       [1, 0, 0, 1, 0, 0, 0, 1],
       [0, 0, 0, 1, 1, 1, 1, 1],
       [0, 1, 1, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 1, 1, 1, 1, 1, 0],
       [0, 0, 1, 0, 1, 1, 1, 0]])

In [ ]:
def contAdp(pop):
  adp = np.zeros(10)
  for x in range(len(pop)):
    for j in range(7):
      if(pop[x, j] == 0) and (pop[x, j+1] == 1):
        adp[x] += 1
  return adp

In [ ]:
def adpUnico(aux):
  adp1 = 0
  for x in range(7):
    if(aux[0,x] == 0) and (aux[0,x+1] == 1):
      adp1 += 1
  return adp1

In [ ]:
def selRoleta(adp):
  roleta = np.zeros(20)
  total = 0
  for x in adp:
    total = total + x
  x = 1
  y = 1
  while((x<20) and (y<10)):
    z = round((adp[y]*20)/total)
    while((z>0) and (x<20)):
      roleta[x] = y
      x += 1
      z -= 1
    y += 1
  z = random.randrange(20)
  return roleta[z]

In [ ]:
def cruzar(pai, mae):
  x = random.randint(1,6)
  f1 = np.concatenate([pai[x:], mae[:x]])
  f2 = np.concatenate([pai[:x], mae[x:]])
  return f1.reshape(1,8), f2.reshape(1,8)

In [ ]:
def mutar(ind, mut):
  for y in range(8):
    x = random.randint(0,1)
    if (x == 0):
      mut[0,y] = ind[0,y]
    elif (ind[0,y] == 0):
      mut[0,y] = 1
    else:
      mut[0,y] = 0

In [ ]:
def maior(adp):
  x = -1
  for elem in adp:
    if(x < elem):
      x = elem
  return x

In [ ]:
ma = np.random.randint(2, size=(1,8))
mb = np.random.randint(2, size=(1,8))
adp = contAdp(pop)
while(maior(adp) != 4):
  xa = int(selRoleta(adp))
  pai = pop[xa]
  xb = int(selRoleta(adp))
  mae = pop[xb]
  f1, f2 = cruzar(pai, mae)
  mutar(f1, ma)
  mutar(f2, mb)
  if (adp[xa] < adpUnico(ma)):
    pop[xa] = ma
  if (adp[xb] < adpUnico(mb)):
    pop[xb] = mb
  adp = contAdp(pop)
print("MAIOR ADP> " , maior(adp))
print(pop)

MAIOR ADP>  4.0
[[1 0 0 1 0 0 1 1]
 [0 0 0 1 0 1 1 0]
 [0 0 1 0 1 0 1 0]
 [1 1 0 1 1 0 1 0]
 [1 0 0 1 0 0 0 1]
 [0 1 1 0 0 0 1 0]
 [0 1 1 0 0 0 1 0]
 [0 1 0 1 0 1 0 1]
 [0 0 1 1 1 1 1 0]
 [0 0 1 0 1 1 1 0]]
