<a href="https://colab.research.google.com/github/leoopl/DataScience/blob/main/Quest%C3%A3o_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install fsspec

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split  
from sklearn.metrics import classification_report, confusion_matrix  
from sklearn import datasets
iris = datasets.load_iris()
irs = pd.DataFrame(iris.data, columns = iris.feature_names)
irs['class'] = iris.target
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn import svm

In [ ]:
irs.head()

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  class
0                5.1               3.5  ...               0.2      0
1                4.9               3.0  ...               0.2      0
2                4.7               3.2  ...               0.2      0
3                4.6               3.1  ...               0.2      0
4                5.0               3.6  ...               0.2      0

[5 rows x 5 columns]

In [ ]:
x = irs.iloc[:, :-1].values
y = irs.iloc[:, 4].values

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3)

scaler = StandardScaler()
scaler.fit(x_train)

x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

classifier = KNeighborsClassifier(n_neighbors = 3)
classifier.fit(x_train, y_train)

y_pred = classifier.predict(x_test)

In [ ]:
print(confusion_matrix(y_test, y_pred))

[[16  0  0]
 [ 0 13  1]
 [ 0  1 14]]


In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       0.93      0.93      0.93        14
           2       0.93      0.93      0.93        15

    accuracy                           0.96        45
   macro avg       0.95      0.95      0.95        45
weighted avg       0.96      0.96      0.96        45



In [ ]:
from sklearn.model_selection import cross_val_score
clf = svm.SVC(gamma='auto')
clf.fit(x_train, y_train)
scores = cross_val_score(clf, irs, irs['class'], cv=5, scoring='accuracy')
print(scores)
scores.mean()

[1. 1. 1. 1. 1.]


1.0